lkimilhol-3-회원도메인설계
jordy-with-friends/jordy-shop pull request #4
Opened 2021-09-06 03:54 UTC by lkimilhol

1. 회의 때 결정 했던  내용들을 토대로 엔티티 생성
2. 원시값 포장이나 패스워드를 구체화 하는 부분은 이슈로 등록 할 예정
3. script에 스키마 생성 쿼리 작성, 플라이웨이에 create table 쿼리 작성만 해둠 (필요한 부분 코멘트 남겨주세요)

2021-09-06 04:04 UTC, bbbnam commented on src/test/java/com/example/jordyshop/domain/MemberTest.java
> +}
마지막줄 공백라인 추가 필요합니닷

2021-09-06 04:04 UTC, bbbnam commented on src/main/java/com/example/jordyshop/domain/Member.java
> +    }
저희 롬복 쓰기로 했으면 @Builder 써서 빌더 패턴쓰는게 가독성에 좋지 않을까요?

2021-09-06 04:05 UTC, lkimilhol commented on src/main/java/com/example/jordyshop/domain/Member.java
> +    }
갠적으로 빌더 패턴을 쓰면 인자로 받아야 할게 모두 체크가 안돼서 약간 안쓰게 되더라구요! 어떤게 좋을지 얘기 해보면 좋을거같아요! 좋은 피드백 감사합니다 ㅋㅋㅋ

2021-09-06 04:06 UTC, lkimilhol commented on src/test/java/com/example/jordyshop/domain/MemberTest.java
> +}
넵! 수정!

2021-09-06 04:11 UTC, jordy-torvalds requested changes
.

2021-09-06 04:11 UTC, jordy-torvalds commented on src/main/resources/db/migration/V1__INIT.sql
> +create table member (id bigint auto_increment, address varchar(255), addressDetail varchar(255), age integer not null, email varchar(255), name varchar(255), nickname varchar(255), password varchar(2
beautify 된 SQL로 바꿔주시면 너무 감사하겠습니다!

2021-09-06 04:11 UTC, jordy-torvalds commented on src/test/java/com/example/jordyshop/domain/MemberTest.java
> +}
근데 그거 뭐 땜에 하는거였죠?

2021-09-06 14:22 UTC, lkimilhol commented on src/main/resources/db/migration/V1__INIT.sql
> +create table member (id bigint auto_increment, address varchar(255), addressDetail varchar(255), age integer not null, email varchar(255), name varchar(255), nickname varchar(255), password varchar(2
수정하였습니다!

2021-09-06 14:23 UTC, lkimilhol commented
회원 테이블의 각 필드는 원시값을 포장하고, 각 포장된 객체들에서 유효성 검사 등이 필요해 보여 이슈 생성을 하였습니다.

2021-09-06 19:54 UTC, jordy-torvalds commented on src/main/resources/db/migration/V1__INIT.sql
> +    password       VARCHAR(20),
단방향 암호화 아웃풋에 따라서 사이즈 조절이 필요할 수 있겠네유 ㅎㅎ..

2021-09-06 19:55 UTC, jordy-torvalds commented
#머지에 동의 합니다

2021-09-06 19:59 UTC, jordy-torvalds approved these changes
확인했습니다!

2021-09-08 00:04 UTC, bbbnam commented on src/main/resources/application.properties
>  spring.jpa.show-sql=true
https://prolog.techcourse.co.kr/posts/1182
https://github.com/raycon/til/issues/64

네이밍 전략 참고 내용입니닷
기본값이라 불필요한 것으로 판단되는데 확인 부탁드립니닷-!
그리고 이것도 마지막줄 공백을 주는게 어떨까요?

2021-09-08 00:08 UTC, bbbnam commented on src/main/resources/db/migration/V1__INIT.sql
> +)
요곳도 마지막줄... ㅠ
이게 이부분이 보여서 좀 ...
![image](https://user-images.githubusercontent.com/39575145/132425268-80eb14d1-6ec6-4792-80e4-d90d70da7d8f.png)

2021-09-08 05:05 UTC, bbbnam commented
저도 머지에 동의합니다-!

2021-09-08 06:25 UTC, merged